#docker-composeのバージョンを指定
version: "3.7"

services:
 app:
  build:
      context: .
      dockerfile: Dockerfile
  container_name: vue
  ports:
    - "18082:8080"
  volumes:
    - ./src:/var/www/html
  tty: true